title = "Flow Across"
baseurl = "http://example.com/"
languageCode = "en-us"
theme = "tailwind"

author = "Dirk Olbrich"
copyright = "Copyright © 2019-2024, Dirk Olbrich, all rights reserved."

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 20

[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
